from tkinter import *
root=Tk()
name=Label(root,text='NAME')
name.grid(row="0",column="0")
e1=Entry(root).grid(row="0",column='1')
password=Label(root,text='PASSWORD')
password.grid(row='1',column='0')
e2=Entry(root).grid(row='1',column='1')
submit=Button(root,text="Submit")
submit.grid(row=2,column=1)
root.mainloop()